apiVersion: apps/v1
kind: Deployment
metadata:
  name: gerdtop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gerdtop
  template:
    metadata:
      labels:
        app: gerdtop
    spec:
      containers:
      - image: okteto.dev/gerdtop:latest
        name: gerdtop
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "088ad55a-75cf-4235-99e1-a469a12410e2"
        - name: Vless_Path
          value: "/vl532sqaw"
        - name: Vmess_UUID
          value: "088ad55a-75cf-4235-99e1-a469a12410e2"
        - name: Vmess_Path
          value: "/vm3542dswef"
        - name: Share_Path
          value: "/v2link"
